way-app/backend/Way/Way/Modulos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'api/list', views.get_rutas_list, name='get_rutas_list'),
]

way-app/backend/Way/Way/Way/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Modulos.urls'))
] 

way-app/backend/Way/Way/django-map-widgets-master/example/cities/urls.py
from django.conf.urls import url
from cities.views import CityCreateView, CityListView, CityDetailView

urlpatterns = [
    url(r'^$', CityListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', CityDetailView.as_view(), name="detail"),
    url(r'^create/$', CityCreateView.as_view(), name="create"),
]

way-app/backend/Way/Way/django-map-widgets-master/example/example/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('cities:list'))),
    url(r'^admin/', admin.site.urls),
    url(r'^cities/', include('cities.urls', namespace='cities')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

way-app/backend/Way/Way/Modulos/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from django_google_maps import fields as map_fields


class PuntosInteres(models.Model):
	
	id_PuntosInteres = models.AutoField(primary_key=True)
	Nombre= models.CharField(max_length=20)
	Descripcion= models.CharField(max_length=20)
	
	def __str__(self):
		return self.Nombre
		

class Fotos(models.Model):
	id_Fotos = models.AutoField(primary_key=True)
	Valor = models.CharField(max_length=100)
	
	def __str__(self):
		return self.Valor

class Rutas(models.Model):
	id_Ruta = models.AutoField(primary_key=True)
	Nombre = models.CharField(max_length=40)
	altitud= models.CharField(max_length=20)
	longitud= models.CharField(max_length=20)
	Archivoruta= models.CharField(max_length=20)
	Descripcion= models.CharField(max_length=20)
	Duracion= models.CharField(max_length=20)

	def __str__(self):
		return self.Nombre

class Rutas_Fotos(models.Model):
	id_Ruta = models.AutoField(primary_key=True)
	idpuntosinteres = models.ForeignKey(PuntosInteres, on_delete=models.CASCADE)
	idFotos = models.ForeignKey(Fotos, on_delete=models.CASCADE)

class Puntosinteres_fotos(models.Model):
	id_PuntosInteres_fotos = models.AutoField(primary_key=True)
	idFotos = models.ForeignKey(Fotos, on_delete=models.CASCADE)
	idRutas = models.ForeignKey(Rutas, on_delete=models.CASCADE)


class Idiomas(models.Model):
	id_Idioma = models.AutoField(primary_key=True)
	Nombre = models.CharField(max_length=100)
	
	def __str__(self):
		return self.Nombre


class Temas(models.Model):
	id_Tema = models.AutoField(primary_key=True)
	Nombre = models.CharField(max_length=100)
	
	def __str__(self):
		return self.Nombre

class Configuraciones(models.Model):
	id_Configuracion = models.AutoField(primary_key=True)
	Nombre = models.CharField(max_length=100)
	idTemas = models.ForeignKey(Temas, on_delete=models.CASCADE,default=1)
	idIdiomas = models.ForeignKey(Idiomas, on_delete=models.CASCADE,default= 1)
	

	def __str__(self):
		return self.Nombre






class Rental(models.Model):
	address = map_fields.AddressField(max_length=200)
	geolocation = map_fields.GeoLocationField(max_length=100)

way-app/backend/Way/Way/django-map-widgets-master/example/cities/models.py
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point

POINT = Point(-104.9903, 39.7392, srid=4326)


class City(models.Model):
    name = models.CharField(max_length=255)
    coordinates = models.PointField(help_text="To generate the map for your location")
    city_hall = models.PointField(blank=True, null=True)

    def __unicode__(self):
        return self.name


class District(models.Model):
    city = models.ForeignKey(City)
    name = models.CharField(max_length=255)
    location = models.PointField(help_text="To generate the map for your location")

    def __unicode__(self):
        return self.name

way-app/backend/Way/Way/django-map-widgets-master/example/cities/forms.py
from django import forms

from cities.models import City
from mapwidgets.widgets import GooglePointFieldWidget, GoogleStaticMapWidget, GoogleStaticOverlayMapWidget


class CityCreateForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ("name", "coordinates", "city_hall")
        widgets = {
            'coordinates': GooglePointFieldWidget,
            'city_hall': GooglePointFieldWidget,
        }


class CityDetailForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ("name", "coordinates", "city_hall")
        widgets = {
            'coordinates': GoogleStaticMapWidget(zoom=12, size="240x240"),
            'city_hall': GoogleStaticOverlayMapWidget(zoom=12, thumbnail_size="50x50", size="640x640"),
        }

way-app/backend/Way/Way/Modulos/views.py
# Create your views here.

from django.shortcuts import render
from django.http import JsonResponse
from .models import Rutas
from .serializers import RutasSerializer
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_protect
from rest_framework.views import APIView


#@api_view(["POST","GET"]) @api_view(["POST", "GET"])
#@api_view (['POST']) 
def index(request):
    rutas_list = Rutas.objects.order_by('-Nombre')
    context = {'rutas_list': rutas_list}
    return render(request, 'Templates/index.html', context)


# Rest api end point
#@api_view(["POST","GET"])
#@api_view (['POST']) 
#@csrf_protect
def get_rutas_list(request):
    """
    Returns Json list of all restaurants
    """
    if request.method == "GET":
        rutas_list = Rutas.objects.order_by('-Nombre')
        serializer = RutasSerializer(rutas_list, many=True)
        return JsonResponse(serializer.data, safe=False)

way-app/backend/Way/Way/django-map-widgets-master/example/cities/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView

from cities.forms import CityCreateForm, CityDetailForm
from cities.models import City


class CityListView(ListView):
    queryset = City.objects.all()
    template_name = "cities/list.html"
    context_object_name = "cities"


class CityDetailView(UpdateView):
    form_class = CityDetailForm
    model = City
    template_name = "cities/detail.html"


class CityCreateView(FormView):
    template_name = "cities/form.html"
    form_class = CityCreateForm
    success_url = reverse_lazy("cities:list")

    def form_valid(self, form):
        form.save()
        return super(CityCreateView, self).form_valid(form)

way-app/backend/Way/Way/django-map-widgets-master/example/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
    <title>Map Widgets - Example Project</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>



    {% block extrahead %}
    {% endblock extrahead %}

</head>
<body>
    <div class="container help-block" >
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

way-app/backend/Way/Way/django-map-widgets-master/example/templates/cities/detail.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block content %}
    {{ form.as_p }}
{% endblock content %}

way-app/backend/Way/Way/django-map-widgets-master/example/templates/cities/form.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}

    <script type="text/javascript">
        $(document).on("google_point_map_widget:marker_create", function (e, lat, lng, locationInputElem, mapWrapID) {
            console.log(locationInputElem); // django widget textarea widget (hidden)
            console.log(lat, lng); // created marker coordinates
            console.log(mapWrapID); // map widget wrapper element ID
        });

        $(document).on("google_point_map_widget:marker_change", function (e, lat, lng, locationInputElem, mapWrapID) {
            console.log(locationInputElem); // django widget textarea widget (hidden)
            console.log(lat, lng);  // changed marker coordinates
            console.log(mapWrapID); // map widget wrapper element ID
        });

        $(document).on("google_point_map_widget:marker_delete", function (e, lat, lng, locationInputElem, mapWrapID) {
            console.log(locationInputElem); // django widget textarea widget (hidden)
            console.log(lat, lng);  // deleted marker coordinates
            console.log(mapWrapID); // map widget wrapper element ID
        })
    </script>
{% endblock extrahead %}

{% block content %}
    <form action="{% url "cities:create" %}" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock content %}

way-app/backend/Way/Way/django-map-widgets-master/example/templates/cities/list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 20px"><a href="{% url "cities:create" %}" class="btn btn-default block">Create</a></div>
        <ul class="block">
            {% for city in cities %}
                <li><a href="{% url "cities:detail" city.id %}">{{ city.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

way-app/backend/Way/Way/django-map-widgets-master/mapwidgets/templates/mapwidgets/google-point-field-inline-widget.html
{% extends "mapwidgets/google-point-field-widget.html" %}

{% block javascript %}
    <script type="application/javascript">

        (function($) {
            var mapOptions = JSON.parse("{{ options|escapejs }}");
            var fieldValue = JSON.parse("{{ field_value|escapejs }}");
            {% if not is_formset_empty_form_template %}

                var widgetData = JSON.parse("{{ js_widget_data|escapejs }}");
                var wrapElemSelector = widgetData.wrapElemSelector;
                var mapElemID = widgetData.mapElemID;
                var googleAutoInputID = widgetData.googleAutoInputID;
                var locationInputID = widgetData.locationInputID;

                var mapWidgetOptions = {
                    locationInput: $(locationInputID),
                    wrapElemSelector: wrapElemSelector,
                    locationFieldValue: fieldValue,
                    mapElement: document.getElementById(mapElemID),
                    mapCenterLocationName: mapOptions.mapCenterLocationName,
                    mapCenterLocation: mapOptions.mapCenterLocation,
                    coordinatesOverlayToggleBtn: $(".mw-btn-coordinates", wrapElemSelector),
                    coordinatesOverlayDoneBtn: $(".mw-btn-coordinates-done", wrapElemSelector),
                    coordinatesOverlayInputs: $(".mw-overlay-input", wrapElemSelector),
                    coordinatesOverlay: $(".mw-coordinates-overlay", wrapElemSelector),
                    myLocationBtn: $(".mw-btn-my-location", wrapElemSelector),
                    addressAutoCompleteInput: document.getElementById(googleAutoInputID),
                    deleteBtn: $(".mw-btn-delete", wrapElemSelector),
                    addMarkerBtn: $(".mw-btn-add-marker", wrapElemSelector),
                    loaderOverlayElem: $(".mw-loader-overlay", wrapElemSelector),
                    zoom: mapOptions.zoom,
                    markerFitZoom: mapOptions.markerFitZoom,
                    GooglePlaceAutocompleteOptions: mapOptions.GooglePlaceAutocompleteOptions,
                    markerCreateTriggerNameSpace: "google_point_map_widget:marker_create",
                    markerChangeTriggerNameSpace: "google_point_map_widget:marker_change",
                    markerDeleteTriggerNameSpace: "google_point_map_widget:marker_delete",
                    placeChangedTriggerNameSpace: "google_point_map_widget:place_changed"
                };
                var widget = new DjangoGooglePointFieldWidget(mapWidgetOptions);

            {% else %}
                var widgetDataTemplate = JSON.parse("{{ js_widget_data|escapejs }}");
                var widgetGenerater = new DjangoMapWidgetGenerater({
                    "widgetDataTemplate": widgetDataTemplate,
                    "mapOptions": mapOptions,
                    "fieldValue": fieldValue
                });
            {% endif %}
        })(jQuery || django.jQuery);
    </script>
{% endblock javascript %}

way-app/backend/Way/Way/django-map-widgets-master/mapwidgets/templates/mapwidgets/google-point-field-widget.html
{% load i18n %}

<div class="mw-wrap" id="{{ name }}-mw-wrap">
    {% block container %}
        <div class="mw-header">
            {% block header %}
                <div class="mw-coordinates-wrap">
                    <a  class="mw-btn mw-btn-primary mw-btn-coordinates">{% trans "Coordinates" %} <i class="icon-down-dir" ></i></a>
                    <div class="mw-coordinates-overlay hide">
                        <label for="{{ name }}-mw-overlay-latitude">
                            {% trans "Latitude:" %}
                            <input type="text" id="{{ name }}-mw-overlay-latitude" class="form-control mw-overlay-input mw-overlay-latitude" placeholder="{% trans 'Ex: 41.015137' %}"/>
                        </label>
                        <label for="{{ name }}-mw-overlay-longitude">
                            {% trans "Longitude:" %}
                            <input type="text" id="{{ name }}-mw-overlay-longitude" class="form-control mw-overlay-input mw-overlay-longitude" placeholder="{% trans 'Ex: 28.979530' %}"/>
                        </label>
                        <a class="mw-btn mw-btn-success mw-btn-coordinates-done pull-right">{% trans "Done" %}</a>
                    </div>
                </div>

                <a class="mw-btn mw-btn-info mw-btn-my-location" >{% trans "Use My Location" %}</a>
                <a class="mw-btn mw-btn-warning mw-btn-add-marker" ><i class="icon-location"></i></a>
                <div class="mw-adress-input-wrap pull-right">
                    <input type="text" class="form-control pull-right" id="{{ name }}-mw-google-address-input" placeholder="{% trans 'Enter or update the address here' %}"/>
                </div>
            {% endblock header %}
        </div>

        <div class="mw-map-wrapper">
            <div class="mw-loader-overlay hide" >
                <div class="mw-loader"></div>
            </div>
            <div id="{{ name }}-map-elem" class="mw-map"></div>
            <div style="display: none" class="hide">
                <textarea id="{{ id }}" name="{{ name }}">{{ serialized }}</textarea>
                {% block extra_input %}
                {% endblock extra_input %}

            </div>
        </div>

        <div class="mw-footer">
            <span class="mw-help-text help-text"></span>
            <a class="mw-btn mw-btn-delete pull-right {{ serialized|yesno:"mw-btn-danger, mw-btn-default disabled" }}" ><i class="icon-trash-empty"></i></a>
        </div>
        <div class="animated-loader"></div>
    {% endblock container %}
</div>

{% block javascript %}
    <script type="application/javascript">
        (function($) {
            var mapOptions = JSON.parse("{{ options|escapejs }}");
            var field_value = JSON.parse("{{ field_value|escapejs }}");

            var wrapElemSelector = "#{{ name }}-mw-wrap";
            var mapElemID = "{{ name }}-map-elem";
            var googleAutoInputID = "{{ name }}-mw-google-address-input";
            var locationInputID = "#{{ id }}";

            var mapWidgetOptions = {
                locationInput: $(locationInputID),
                wrapElemSelector: wrapElemSelector,
                locationFieldValue: field_value,
                mapElement: document.getElementById(mapElemID),
                mapCenterLocationName: mapOptions.mapCenterLocationName,
                mapCenterLocation: mapOptions.mapCenterLocation,
                coordinatesOverlayToggleBtn: $(".mw-btn-coordinates", wrapElemSelector),
                coordinatesOverlayDoneBtn: $(".mw-btn-coordinates-done", wrapElemSelector),
                coordinatesOverlayInputs: $(".mw-overlay-input", wrapElemSelector),
                coordinatesOverlay: $(".mw-coordinates-overlay", wrapElemSelector),
                myLocationBtn: $(".mw-btn-my-location", wrapElemSelector),
                addressAutoCompleteInput: document.getElementById(googleAutoInputID),
                deleteBtn: $(".mw-btn-delete", wrapElemSelector),
                addMarkerBtn: $(".mw-btn-add-marker", wrapElemSelector),
                loaderOverlayElem: $(".mw-loader-overlay", wrapElemSelector),
                zoom: mapOptions.zoom,
                markerFitZoom: mapOptions.markerFitZoom,
                GooglePlaceAutocompleteOptions: mapOptions.GooglePlaceAutocompleteOptions,
                markerCreateTriggerNameSpace: "google_point_map_widget:marker_create",
                markerChangeTriggerNameSpace: "google_point_map_widget:marker_change",
                markerDeleteTriggerNameSpace: "google_point_map_widget:marker_delete",
                placeChangedTriggerNameSpace: "google_point_map_widget:place_changed"
            };
            var widget = new DjangoGooglePointFieldWidget(mapWidgetOptions);
            {% block extra_javascript %}

            {% endblock %}
        })(jQuery || django.jQuery);
    </script>
{% endblock javascript %}

way-app/backend/Way/Way/django-map-widgets-master/mapwidgets/templates/mapwidgets/google-static-map.html
{% if value %}
    <a href="{{ image_url }}" target="_blank" class="static-map-link"><img src="{{ image_url }}"></a>
{% else %}
    <img src="{{ image_url }}" class="no-map-image">
{% endif %}
<input type="hidden" name="{{ name }}" value="{{ value }}"/>

way-app/backend/Way/Way/django-map-widgets-master/mapwidgets/templates/mapwidgets/google-static-overlay-map.html
{% if value %}
    <a href="{{ image_url }}" class="map-widget-overlay-link"><img src="{{ thumbnail_url }}"></a>
{% else %}
    <img src="{{ image_url }}" class="no-map-image">
{% endif %}
<input type="hidden" name="{{ name }}" value="{{ value }}"/>